Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 10
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	2	metadata
	3

[Thu Nov  5 09:52:58 2020]
rule metadata:
    output: results/Metadata/SRR8094770.json
    log: info/logs/SRR8094770.metadata.log
    jobid: 2
    benchmark: info/benchmark/SRR8094770.metadata.log
    wildcards: sample=SRR8094770
    threads: 4

[Thu Nov  5 09:52:58 2020]
rule metadata:
    output: results/Metadata/SRR12845350.json
    log: info/logs/SRR12845350.metadata.log
    jobid: 1
    benchmark: info/benchmark/SRR12845350.metadata.log
    wildcards: sample=SRR12845350
    threads: 4

[Thu Nov  5 09:52:58 2020]
Error in rule metadata:
    jobid: 1
    output: results/Metadata/SRR12845350.json
[Thu Nov  5 09:52:58 2020]
    log: info/logs/SRR12845350.metadata.log (check log file(s) for error message)
Error in rule metadata:

    jobid: 2
    output: results/Metadata/SRR8094770.json
    log: info/logs/SRR8094770.metadata.log (check log file(s) for error message)

RuleException:
URLError in line 42 of /home/kasper/Git_repositories/LiverDB/workflow/Snakefile.py:
<urlopen error [Errno 2] No such file or directory: '/home/kasper/Git_repositories/LiverDB/workflow/workflow/scripts/sradata.py'>
  File "/home/kasper/Git_repositories/LiverDB/workflow/Snakefile.py", line 42, in __rule_metadata
  File "/home/kasper/miniconda3/lib/python3.7/urllib/request.py", line 222, in urlopen
  File "/home/kasper/miniconda3/lib/python3.7/urllib/request.py", line 525, in open
  File "/home/kasper/miniconda3/lib/python3.7/urllib/request.py", line 543, in _open
  File "/home/kasper/miniconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
  File "/home/kasper/miniconda3/lib/python3.7/urllib/request.py", line 1453, in file_open
  File "/home/kasper/miniconda3/lib/python3.7/urllib/request.py", line 1492, in open_local_file
  File "/home/kasper/miniconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
RuleException:
URLError in line 42 of /home/kasper/Git_repositories/LiverDB/workflow/Snakefile.py:
<urlopen error [Errno 2] No such file or directory: '/home/kasper/Git_repositories/LiverDB/workflow/workflow/scripts/sradata.py'>
  File "/home/kasper/Git_repositories/LiverDB/workflow/Snakefile.py", line 42, in __rule_metadata
  File "/home/kasper/miniconda3/lib/python3.7/urllib/request.py", line 222, in urlopen
  File "/home/kasper/miniconda3/lib/python3.7/urllib/request.py", line 525, in open
  File "/home/kasper/miniconda3/lib/python3.7/urllib/request.py", line 543, in _open
  File "/home/kasper/miniconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
  File "/home/kasper/miniconda3/lib/python3.7/urllib/request.py", line 1453, in file_open
  File "/home/kasper/miniconda3/lib/python3.7/urllib/request.py", line 1492, in open_local_file
  File "/home/kasper/miniconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/kasper/Git_repositories/LiverDB/workflow/.snakemake/log/2020-11-05T095258.648207.snakemake.log
